### ISSUE TITLE
Track after identity is not logged in MoEngage, but logged in Segment

### ISSUE THREAD

**Issue by ladanazita** [segment-integrations/analytics-ios-integration-moengage#3] opened 2015-12-08 19:26 UTC
The work around a user has done is implementing a delay in between the identity and track events.

**Comment by gautamMoEngage** [comment] 2015-12-10 08:16
@f2prateek - There's a significant delay between identify calls getting to the MoEngage SDK. The queueing mechanism takes upto 5 secs to get the identify callbacks to the SDK. I also think they reset the user when they send the identify call, which results in change in identity of the user and hence the loss of the event.
Can you please check if the callback can send the data quicker ? I don't have time right now to try and work on this in Segment's SDK, else I gladly would have.

**Comment by f2prateek** [comment] 2015-12-10 09:46
Hmm... I've never seen a delay that long. It's possible it could happen when the device had slow internet connection when it launches for the very first time, but subsequent runs should be quick (just tested it and the behaviour is consistent with what I said).

I don't think in this case the user is not calling reset after identify. @ladanazita can you confirm?

@gautamMoEngage Since they're not calling reset, why would the MoEngage SDK drop the event? Not sure why the delay really matters, a track event could come minutes after an identify call and the integration should not drop it.

@ladanazita can you also ask for debug logs?

**Comment by ladanazita** [comment] 2015-12-11 17:25
@f2prateek Just confirmed and they are not calling reset after identify. still waiting on their logs

**Comment by ladanazita** [comment] 2015-12-14 06:58
@f2prateek here are the debug logs 

[Segments Track Event Delay Issue Debug Log.pdf](https://github.com/segment-integrations/analytics-ios-integration-moengage/files/60882/Segments.Track.Event.Delay.Issue.Debug.Log.pdf)

**Comment by f2prateek** [comment] 2015-12-14 12:32
@gautamMoEngage @ladanazita From the logs you can clearly see that the Segment SDK is forwarding the events to MoEngage.

Track:

> 2015-12-14 11:36:40.261 Wynk Movies[3488:611302] Running: track: with
> arguments (
>  "<SEGTrackPayload: 0x175e50410>"
> ) on integration: MoEngage

Flush:

> 2015-12-14 11:36:40.262 Wynk Movies[3488:611302] Running: flush with
> arguments (null) on integration: MoEngage

Identify:

> 2015-12-14 11:36:41.370 Wynk Movies[3488:611294] Running: identify:
> with arguments (
>  "<SEGIdentifyPayload: 0x175e48fa0>"
> ) on integration: MoEngage

You can also see that there is a reset call, which is somewhere later, after some track calls and before a few others as well. 

> 2015-12-14 11:37:01.145 Wynk Movies[3488:611294] Running: reset with
> arguments (null) on integration: MoEngage

There are too many events in this log and it is not an isolated test case. It's unclear which track event the customer is talking about (is it before the reset or after?). If you can clarify with the customer which track call exactly is showing up in MoEngage and which isn't, then maybe MoEngage can debug it further.

The only thing I can think of (again without enough actionable information from the customer) is possibly that the `resetUser` method in MoEngage doesn't upload events in the queue, which is why the customer isn't seeing some events in MoEngage. @gautamMoEngage If that's the case, then we can call `syncNow` in the reset method of the integration.

**Comment by gautamMoEngage** [comment] 2015-12-15 10:28
@f2prateek 
Let's say there are 2 users - A and B. A did some events and called resetUser.
Now, the 1st thing resetUser does is syncNow. It sends all events of A to MoEngage. But if any events occur while resetting the user (1-2 secs), they are gone, since they can't be attribute to either of the users in case of Segment integration. 
The issue is that because of the 1-3 secs delay of events being passed onto us, the events done by the user A, if they come after a delay, uploading them will result in attribution of those events to user B, which might not be correct. 

There are only 2 ways to fix this:
1. Segment sends us events as and when they happen, minimal delay. 
2. After resetUser, they send the next track event after a couple of seconds. (The client has confirmed that this works).

Maybe I am incorrect and there is a better way. Could you let me know how Segment handles this ?

Also, there is an issue on our end where we discard any events happening while resetUser, but the underlying problem is not only that. It is that + the delay in sending events from Segment to MoEngage. 

I will fix the problem on my end and release by tomorrow.

**Comment by f2prateek** [comment] 2015-12-15 15:40
> Let's say there are 2 users - A and B. A did some events and called resetUser. Now, the 1st thing resetUser does is syncNow. It sends all events of A to MoEngage.

 All good!

> But if any events occur while resetting the user (1-2 secs), they are gone, since they can't be attribute 
> to either of the users in case of Segment integration. 

This is where I lose you. Why? This sounds like a MoEngage issue to me.

> The issue is that because of the 1-3 secs delay of events being passed onto us, the events done by the user A, if they come after a delay, uploading them will result in attribution of those events to user B, which might not be correct.

You're conflating delay (which again shouldn't matter) with ordering. There is no situation under which an event from user A will be sent to the MoEngage integration after or during a `reset` call.

So just to clarify, in this case:
1. `[[SEGAnalytics sharedAnalytics] track:@"foo"];`
2. `[[SEGAnalytics sharedAnalytics] reset];`
3. `[[SEGAnalytics sharedAnalytics] track:@"bar"];`

This is approximately how we'll call the MoEngage integration in pseudo-code:
1. `[SEGMoEngageIntegration track:@"foo"];`
2. `[SEGMoEngageIntegration reset];`
3. `[SEGMoEngageIntegration track:@"bar"];`

You're saying event `foo` might be associated with user B instead of user A because of the delay? Why is that? Even the delay was 100 days, MoEngage would see the events in order - track, reset and then track and it should not be mixing the 2 datasets. Unless we were sending reset, and then the 2 tracks, I don't see why MoEngage would mix this up. Ignoring the fact that the latency is never consistently in the 1-3 second range as you keep mentioning, my point stands that even if the delay is unusually large, this shouldn't be happening.

You also keep mentioning "during resetUser", but I wanted to clarify that we only ever call a single method at a time on an integration. So in this case, we'll never call track when we are calling reset on the MoEngage integration.

**Comment by gautamMoEngage** [comment] 2015-12-22 12:45
@f2prateek - As I said, there is a MoEngage issue, where we lose an event during resetUser, which is 2 api calls, one to flush the data and another for new device creation. 
I've fixed that issue and pushed to Cocoapods.

Regardless, the client is having issues which I can't work out on why, reason being that I had made a sample project which has MoEngage integrated via Segment, and everything worked fine then, which they've confirmed. (This was 15 days ago).

Also, on the below

This is approximately how we'll call the MoEngage integration in pseudo-code:

[SEGMoEngageIntegration track:@"foo"];
[SEGMoEngageIntegration reset];
[SEGMoEngageIntegration track:@"bar"];
You're saying event foo might be associated with user B instead of user A because of the delay? Why is that? Even the delay was 100 days, MoEngage would see the events in order - track, reset and then track and it should not be mixing the 2 datasets. Unless we were sending reset, and then the 2 tracks, I don't see why MoEngage would mix this up. Ignoring the fact that the latency is never consistently in the 1-3 second range as you keep mentioning, my point stands that even if the delay is unusually large, this shouldn't be happening.

Reset is a method and not an event for us. Reset is a pair of api calls. User identity changes when you call the method. So if "foo" event comes to MoEngage from Segment, after reset is called, it goes to user B. Part of the reason is , if someone does 5 resets, we don't wish to maintain 5 data sets.

**Comment by f2prateek** [comment] 2015-12-22 19:14
@gautamMoEngage That makes sense but "So if "foo" event comes to MoEngage from Segment, after reset is called, " - that is definitely not happening.

Like I said you are referring to ordering, and not latency. As I shared in the pseduo-code, we are calling  `[SEGMoEngageIntegration track:@"foo"];` and then `[SEGMoEngageIntegration reset];` (in that order only), which is why event `foo` should always be for User A and not User B regardless of latency.

**Comment by gautamMoEngage** [comment] 2015-12-22 21:18
@f2prateek - Perfect then. We are good. Please merge the pull request. Also, how and when can we transfer the owner to MoEngage for our specific repo? Let me know if we need to put in a request for the same. Thanks.

**Comment by f2prateek** [comment] 2015-12-24 00:04
@gautamMoEngage The PR is still waiting resolution on this https://github.com/segment-integrations/analytics-ios-integration-moengage/pull/2#discussion_r47204698.

**Comment by hankim813** [comment] 2016-04-18 23:15
fixed in https://github.com/segment-integrations/analytics-ios-integration-moengage/pull/2

**Closed as completed by hankim813** 2016-04-18 23:15 UTC
